export const REQUEST_ALL_PRODUCTS = "REQUEST_ALL_PRODUCTS";
export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_PRODUCTS_SUCCESS";
export const REQUEST_PRODUCTS_FAILURE = "REQUEST_PRODUCTS_FAILURE";

export const REQUEST_PRODUCT_DETAILS = "REQUEST_PRODUCT_DETAILS";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
